### ISSUE TITLE
User Story #2

### ISSUE THREAD

**Issue by amynmerchant** [asham28/goodEats#2]
## User Story
As a user, I want to add my selected recipes to a day for a weekly planner.

## Acceptance Criteria
- [ ] Based on user choice, allow the user to assign the selected recipe to a particular day of the week.
- [ ] Allow selection of only 1 recipe per day (restriction - "only 1 right answer checkbox").

**Comment by asham28** [comment]
We are no longer doing a meal plan as part of our MVP
