### ISSUE TITLE
User Story #3

### ISSUE THREAD

**Issue by amynmerchant** [asham28/goodEats#3]
## User Story
As a user, I want to be able to edit my weekly planner if I want to eat something else or skip as I have leftovers.

## Acceptance Criteria
- [ ] Remove button
- [ ] To select an alternative recipe, add button redirects to the initial search page.
- [ ] If nothing populated, add button is clickable, else not/alternative logic (TBD).

**Comment by asham28** [comment]
No longer doing a meal plan as part of our MVP
